name: 'Release tag'
description: 'Release verion to npm from git tags'
author: 'Rabbit <yfhj1990@hotmail.com>'
inputs:
  context:
    description: 'Bundle context, default to current directory'
    default: '.'
  title:
    description: 'Release title'
  body:
    description: 'Release body'
  packages:
    description: 'Also publish to GitHub Packages Registry'
    default: true
  delete-branch:
    description: 'Delete branch when publish successful'
    default: true
runs:
  using: 'node12'
  main: '../dist/release-tag.js'